services:
  - type: web
    name: vaultx-banking-api
    env: docker
    plan: starter
    dockerfilePath: Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: vaultx-postgres
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: FRONTEND_URL
        value: https://vaultx-banking-frontend.onrender.com
    healthCheckPath: /api/accounts/count

databases:
  - name: vaultx-postgres
    plan: starter
