spring:
  application:
    name: bank-management-system
  
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/bank_management}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      connection-timeout: 30000
      idle-timeout: 300000
      max-lifetime: 600000
      leak-detection-threshold: 60000
      auto-commit: true
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
        connection:
          provider_disables_autocommit: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  
  security:
    user:
      name: ${ADMIN_USERNAME:admin}
      password: ${ADMIN_PASSWORD:admin}

server:
  port: 8080

logging:
  level:
    com.bankmanagement: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:change-this-in-production}
  expiration: 86400000 # 24 hours in milliseconds
